### PR TITLE
Create esMX.lua

### PR DESCRIPTION
**Pull request by woopydalan**

### CODE REVIEW

**Comment by Pazza** [comment]
Since the translations are identical, I'd hate to see two separate files. Can you test if cloning the table before adding the translation resolves the issue?

**Comment by Pazza** [comment]
What's happening is, if the locale being registered isn't the current locale, it is clearing out the table to save memory. That is why it is not working. I will update to load the the two conditionally using WIM.getLocale().

**Comment by woopydalan** [comment]
@Pazza Ok when you add that in I will test, or you can just change your locale and test yourself.

**Comment by Pazza** [comment]
@woopydalan try the latest alpha on curse please.

**Comment by woopydalan** [comment]
@Pazza Hi I tested and it works for both esES and esMX. I will close out the pull requests and issue.

**Pull request closed without merging**
