### PR TITLE
ReglohPri_Deprecated_GuildRoster

### PR DESCRIPTION
**Pull request by ReglohPri**
Since Patch 8.2.0 is GuildRoster() deprecated.
I changed it to C_GuildInfo.GuildRoster().

Tested on the PTR Server for Shadowlands.
I'm not sure if it works under classic

Merge first my Patches for 9.0.1 and then this here.

### CODE REVIEW

**Comment by MysticalOS** [comment]
the 8.2.0 change needs to consider that classic is based off 8.1.5 and doesn't have that change.

**Comment by ReglohPri** [comment]
Then we need our own variable to distinguish the rest from Classic

**Comment by MysticalOS** [comment]
just do a simple upvalue above the usage along the lines of
local GuildRoster = _G.GuildRoster or _G.C_GuildInfo.GuildRoster()
or whatever correct formatting is

**Comment by ReglohPri** [comment]
I have to do it like this, otherwise my debugger will complain.

if (select (4, GetBuildInfo ()) <= 19999) then
   - for classic
   _G.GuildRoster ();
else
   _G.C_GuildInfo.GuildRoster ();
end

**Comment by MysticalOS** [comment]
I still think it's better to see if GuildRoster function exists, in 9.0 the deprecated functions will be deleted, so they will be nil. This ensures future compat automatically if/when classic updates to a newer code base than 8.1.5

that fix would need to be refixed. although I guess that's not a bad thing since if classic does update to later code base the entire check should just be removed. So second thought yeah that'd probably be fine because then at least we'll be forced to remember to remove it. :D

**Comment by ReglohPri** [comment]
So, i will close this pull request and create a new pull request with my changes

**Pull request closed without merging**
